from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE_FILE = ROOT / "package.json"
TARGET_CONTRACT = ROOT / "supabase" / "schema" / "target_schema_v1.json"
PHASE_CONTRACT = ROOT / "supabase" / "schema" / "s2_b2_teachers_contract.json"
MIGRATIONS_DIR = ROOT / "supabase" / "migrations"
WORKFLOW_FILE = ROOT / ".github" / "workflows" / "quality-pages.yml"
VISIBLE_WORKFLOW_FILE = ROOT / "GITHUB_WORKFLOW_VISIBLE" / "quality-pages.yml"
LIVE_ACCEPTANCE = ROOT / "supabase" / "tests" / "s2_b2_live_acceptance.sql"

B1_MIGRATION = "20260901120000_s2_b1_core_identity_tenancy.sql"
B2_MIGRATION = "20260901190000_s2_b2_teachers_domain.sql"
EXPECTED_TARGET_SHA256 = "84ba44b8104d09d62095c4af00a40d413ddc78fb1b2b251af1487d439368ecda"
EXPECTED_B1_SHA256 = "53a20ade59193cc37ce9aa5935fb6739e76262df6cf9fc2350c6399d6a3a0de2"
EXPECTED_B2_SHA256 = "65030ee568719c5da6a010522c401e52b7b56b362a2547e02ed0f311c4d5e78b"
EXPECTED_TABLES = {"teachers", "teacher_profiles", "teacher_years", "teacher_cv_items"}


def fail(message: str) -> None:
    raise SystemExit(f"FAIL: {message}")


def compact(text: str) -> str:
    text = re.sub(r"--[^\n]*", " ", text)
    return re.sub(r"\s+", " ", text).strip().lower()


def table_body(sql: str, table: str) -> str:
    match = re.search(rf"create\s+table\s+public\.{re.escape(table)}\s*\((.*?)\n\);", sql, flags=re.I | re.S)
    if not match:
        fail(f"missing CREATE TABLE public.{table}")
    return compact(match.group(1))


def require(sql: str, fragment: str, label: str) -> None:
    if compact(fragment) not in sql:
        fail(f"{label} missing required fragment: {fragment}")


def main() -> None:
    required = [PACKAGE_FILE, TARGET_CONTRACT, PHASE_CONTRACT, WORKFLOW_FILE, VISIBLE_WORKFLOW_FILE, LIVE_ACCEPTANCE]
    for path in required:
        if not path.exists(): fail(f"required S2-B2 file missing: {path.relative_to(ROOT)}")

    package = json.loads(PACKAGE_FILE.read_text(encoding="utf-8"))
    version = package.get("version", "0.0.0")
    try:
        version_tuple = tuple(int(part) for part in version.split(".")[:3])
    except ValueError:
        fail(f"invalid package version: {version}")
    if version_tuple < (0, 18, 0): fail("S2-B2 requires package version >= 0.18.0")

    if hashlib.sha256(TARGET_CONTRACT.read_bytes()).hexdigest() != EXPECTED_TARGET_SHA256:
        fail("S2-A frozen target schema changed during S2-B2")

    b1 = MIGRATIONS_DIR / B1_MIGRATION
    b2 = MIGRATIONS_DIR / B2_MIGRATION
    if not b1.exists() or not b2.exists(): fail("S2-B1 and S2-B2 migrations must both exist")
    if hashlib.sha256(b1.read_bytes()).hexdigest() != EXPECTED_B1_SHA256:
        fail("approved S2-B1 migration changed after S2-B2")
    if hashlib.sha256(b2.read_bytes()).hexdigest() != EXPECTED_B2_SHA256:
        fail("approved S2-B2 migration changed after its live acceptance")
    migrations = sorted(p.name for p in MIGRATIONS_DIR.glob("*.sql") if p.is_file())
    if len(migrations) < 2 or migrations[:2] != [B1_MIGRATION, B2_MIGRATION]:
        fail(f"S2-B1/B2 migration history changed unexpectedly: {migrations}")

    contract = json.loads(PHASE_CONTRACT.read_text(encoding="utf-8"))
    if contract.get("phase") != "S2-B2" or contract.get("project_version") != "0.18.0": fail("invalid S2-B2 contract identity")
    if contract.get("frozen_schema_contract_sha256") != EXPECTED_TARGET_SHA256: fail("S2-B2 contract not pinned to S2-A")
    if contract.get("required_prior_migration", {}).get("sha256") != EXPECTED_B1_SHA256: fail("S2-B2 contract not pinned to approved S2-B1")
    for key in ("runtime_switch_allowed","data_migration_allowed","rls_allowed"):
        if contract.get(key) is not False: fail(f"{key} must remain false in S2-B2")
    if contract.get("deny_by_default_until_s2_c") is not True: fail("S2-B2 must remain deny-by-default")

    raw = b2.read_text(encoding="utf-8")
    sql = compact(raw)
    created = set(re.findall(r"create\s+table\s+public\.([a-z_][a-z0-9_]*)", sql))
    if created != EXPECTED_TABLES: fail(f"S2-B2 may create only teacher domain tables; got {sorted(created)}")

    for label, pattern in {
        "RLS enablement": r"enable\s+row\s+level\s+security",
        "RLS policy": r"create\s+policy",
        "runtime function": r"create\s+(?:or\s+replace\s+)?function",
        "data insert": r"insert\s+into",
        "data update": r"update\s+public\.",
        "data delete": r"delete\s+from",
        "auth mutation": r"auth\.users\s*(?:set|values)",
        "storage mutation": r"storage\.objects",
    }.items():
        if re.search(pattern, sql, flags=re.I): fail(f"forbidden S2-B2 SQL detected: {label}")

    teachers = table_body(raw, "teachers")
    for frag in [
        "id bigint generated by default as identity primary key",
        "school_id uuid not null references public.schools(id) on delete cascade",
        "name text not null", "is_active boolean not null default true",
        "unique (school_id, id)", "check (btrim(name) <> '')",
    ]: require(teachers, frag, "teachers")
    for forbidden_col in ("subject", "experience_years", "workload", "grades", "responsibilities"):
        if re.search(rf"\b{forbidden_col}\s+", teachers): fail(f"annual attribute leaked back into teachers: {forbidden_col}")

    profiles = table_body(raw, "teacher_profiles")
    for frag in ["teacher_id bigint primary key", "school_id uuid not null", "employee_number text", "school_join_year smallint",
                 "foreign key (school_id, teacher_id) references public.teachers (school_id, id) on delete cascade",
                 "school_join_year is null or school_join_year between 1950 and 2100"]:
        require(profiles, frag, "teacher_profiles")

    years = table_body(raw, "teacher_years")
    for frag in ["primary key (school_id, academic_year_id, teacher_id)",
                 "foreign key (school_id, academic_year_id) references public.academic_years (school_id, id) on delete cascade",
                 "foreign key (school_id, teacher_id) references public.teachers (school_id, id) on delete cascade",
                 "experience_years is null or experience_years between 0 and 60",
                 "workload is null or workload between 0 and 40"]:
        require(years, frag, "teacher_years")

    cv = table_body(raw, "teacher_cv_items")
    for frag in ["id bigint generated by default as identity primary key", "school_id uuid not null", "teacher_id bigint not null",
                 "item_type in ('qualification', 'course', 'achievement', 'experience')",
                 "start_year is null or start_year between 1950 and 2100",
                 "end_year is null or end_year between 1950 and 2100",
                 "start_year is null or end_year is null or end_year >= start_year",
                 "foreign key (school_id, teacher_id) references public.teachers (school_id, id) on delete cascade"]:
        require(cv, frag, "teacher_cv_items")

    for frag, label in [
        ("create unique index uq_teacher_profiles_employee_number_per_school on public.teacher_profiles (school_id, btrim(employee_number)) where employee_number is not null and btrim(employee_number) <> ''", "employee number uniqueness"),
        ("alter table public.school_memberships add constraint school_memberships_teacher_fk foreign key (school_id, teacher_id) references public.teachers (school_id, id) on delete restrict", "membership teacher same-school FK"),
        ("create index idx_teacher_years_teacher on public.teacher_years (school_id, teacher_id, academic_year_id)", "teacher years FK index"),
        ("create index idx_teacher_cv_items_teacher on public.teacher_cv_items (school_id, teacher_id, id)", "teacher CV FK index"),
    ]: require(sql, frag, label)

    for table in sorted(EXPECTED_TABLES):
        require(sql, f"revoke all on table public.{table} from public, anon, authenticated", f"deny-by-default {table}")
    for seq in ("teachers_id_seq", "teacher_cv_items_id_seq"):
        require(sql, f"revoke all on sequence public.{seq} from public, anon, authenticated", f"deny-by-default {seq}")

    if not sql.startswith("begin;") or not sql.endswith("commit;"): fail("S2-B2 migration must use one explicit transaction")


    acceptance = compact(LIVE_ACCEPTANCE.read_text(encoding="utf-8"))
    for fragment in [
        "pass: s2-b2 live acceptance",
        "rollback;",
        "school_memberships_teacher_fk",
        "grantee in ('anon','authenticated')",
        "exception when foreign_key_violation",
        "exception when check_violation",
    ]:
        require(acceptance, fragment, "S2-B2 live acceptance")
    for pattern, label in [
        (r"insert\s+into\s+auth\.", "auth mutation"),
        (r"update\s+auth\.", "auth mutation"),
        (r"delete\s+from\s+auth\.", "auth mutation"),
        (r"storage\.objects", "storage mutation"),
    ]:
        if re.search(pattern, acceptance, flags=re.I):
            fail(f"forbidden live-acceptance operation: {label}")

    workflow = WORKFLOW_FILE.read_text(encoding="utf-8")
    visible = VISIBLE_WORKFLOW_FILE.read_text(encoding="utf-8")
    if workflow != visible: fail("visible workflow copy is not byte-identical")
    if "python scripts/check_supabase_s2_b2.py" not in workflow: fail("CI does not execute S2-B2 contract")

    print("PASS: Marsad Phase S2-B2 teachers domain migration contract")
    print(f"INFO: migration_files={len(migrations)} s2_b2_new_tables=4 same_school_fk=PASS runtime_switch=0 data_migration=0 rls=0")
    print("INFO: annual_teacher_attributes=teacher_years deny_by_default=PASS frozen_schema=PASS")


if __name__ == "__main__":
    main()
