-- Marsad Al-Injazat — Phase S2-B1
-- Core PostgreSQL identity and tenancy foundation.
-- Runtime remains React -> FastAPI -> SQLite. RLS arrives in S2-C.

begin;

create table public.schools (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint schools_name_nonblank check (btrim(name) <> '')
);

create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    display_name text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint profiles_display_name_nonblank check (display_name is null or btrim(display_name) <> '')
);

create table public.school_memberships (
    school_id uuid not null references public.schools(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    -- The same-school FK to public.teachers is intentionally deferred to S2-B2,
    -- because the teachers table does not exist in S2-B1 yet.
    teacher_id bigint,
    role text not null,
    status text not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint school_memberships_pkey primary key (school_id, user_id),
    constraint school_memberships_role_check check (
        role in ('owner', 'admin', 'lead_teacher', 'teacher', 'viewer')
    ),
    constraint school_memberships_status_check check (
        status in ('active', 'invited', 'suspended')
    )
);

create index idx_school_memberships_user_id
    on public.school_memberships (user_id);

create index idx_school_memberships_teacher_id
    on public.school_memberships (teacher_id)
    where teacher_id is not null;

create table public.academic_years (
    id bigint generated by default as identity primary key,
    school_id uuid not null references public.schools(id) on delete cascade,
    label text not null,
    start_year smallint not null,
    end_year smallint not null,
    is_current boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint academic_years_end_year_check check (end_year = start_year + 1),
    constraint academic_years_label_format_check check (label ~ '^[0-9]{4}/[0-9]{4}$'),
    constraint academic_years_label_matches_years_check check (
        label = start_year::text || '/' || end_year::text
    ),
    constraint academic_years_school_label_key unique (school_id, label),
    constraint academic_years_school_id_id_key unique (school_id, id)
);

create unique index uq_academic_years_one_current_per_school
    on public.academic_years (school_id)
    where is_current;

-- S2-B1 is intentionally deny-by-default until S2-C installs RLS policies.
-- Do not expose these tables through the browser Data API yet.
revoke all on table public.schools from public, anon, authenticated;
revoke all on table public.profiles from public, anon, authenticated;
revoke all on table public.school_memberships from public, anon, authenticated;
revoke all on table public.academic_years from public, anon, authenticated;
revoke all on sequence public.academic_years_id_seq from public, anon, authenticated;

commit;
