-- Marsad Al-Injazat — Phase S2-B2
-- Teachers domain migration. S2-B1 core identity/tenancy must already exist.
-- Runtime remains React -> FastAPI -> SQLite. RLS arrives in S2-C.

begin;

create table public.teachers (
    id bigint generated by default as identity primary key,
    school_id uuid not null references public.schools(id) on delete cascade,
    name text not null,
    specialization text,
    qualification text,
    email text,
    phone text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint teachers_name_nonblank check (btrim(name) <> ''),
    constraint teachers_school_id_id_key unique (school_id, id)
);

create index idx_teachers_school_active
    on public.teachers (school_id, is_active, id);

create table public.teacher_profiles (
    teacher_id bigint primary key,
    school_id uuid not null,
    employee_number text,
    school_join_year smallint,
    professional_summary text,
    updated_at timestamptz not null default now(),
    constraint teacher_profiles_teacher_fk
        foreign key (school_id, teacher_id)
        references public.teachers (school_id, id)
        on delete cascade,
    constraint teacher_profiles_school_join_year_check
        check (school_join_year is null or school_join_year between 1950 and 2100)
);

create index idx_teacher_profiles_school_id
    on public.teacher_profiles (school_id);

create unique index uq_teacher_profiles_employee_number_per_school
    on public.teacher_profiles (school_id, btrim(employee_number))
    where employee_number is not null and btrim(employee_number) <> '';

create table public.teacher_years (
    school_id uuid not null,
    academic_year_id bigint not null,
    teacher_id bigint not null,
    subject text,
    experience_years smallint,
    workload smallint,
    grades text,
    responsibilities text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint teacher_years_pkey
        primary key (school_id, academic_year_id, teacher_id),
    constraint teacher_years_academic_year_fk
        foreign key (school_id, academic_year_id)
        references public.academic_years (school_id, id)
        on delete cascade,
    constraint teacher_years_teacher_fk
        foreign key (school_id, teacher_id)
        references public.teachers (school_id, id)
        on delete cascade,
    constraint teacher_years_experience_years_check
        check (experience_years is null or experience_years between 0 and 60),
    constraint teacher_years_workload_check
        check (workload is null or workload between 0 and 40)
);

create index idx_teacher_years_teacher
    on public.teacher_years (school_id, teacher_id, academic_year_id);

create table public.teacher_cv_items (
    id bigint generated by default as identity primary key,
    school_id uuid not null,
    teacher_id bigint not null,
    item_type text not null,
    title text not null,
    organization text,
    start_year smallint,
    end_year smallint,
    description text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint teacher_cv_items_teacher_fk
        foreign key (school_id, teacher_id)
        references public.teachers (school_id, id)
        on delete cascade,
    constraint teacher_cv_items_item_type_check
        check (item_type in ('qualification', 'course', 'achievement', 'experience')),
    constraint teacher_cv_items_title_nonblank
        check (btrim(title) <> ''),
    constraint teacher_cv_items_start_year_check
        check (start_year is null or start_year between 1950 and 2100),
    constraint teacher_cv_items_end_year_check
        check (end_year is null or end_year between 1950 and 2100),
    constraint teacher_cv_items_year_order_check
        check (start_year is null or end_year is null or end_year >= start_year)
);

create index idx_teacher_cv_items_teacher
    on public.teacher_cv_items (school_id, teacher_id, id);

-- Complete the teacher-account link deferred by S2-B1. RESTRICT is deliberate:
-- unlink the membership before deleting a teacher identity tied to an account.
alter table public.school_memberships
    add constraint school_memberships_teacher_fk
    foreign key (school_id, teacher_id)
    references public.teachers (school_id, id)
    on delete restrict;

-- S2-B2 remains deny-by-default until S2-C installs RLS policies.
revoke all on table public.teachers from public, anon, authenticated;
revoke all on table public.teacher_profiles from public, anon, authenticated;
revoke all on table public.teacher_years from public, anon, authenticated;
revoke all on table public.teacher_cv_items from public, anon, authenticated;
revoke all on sequence public.teachers_id_seq from public, anon, authenticated;
revoke all on sequence public.teacher_cv_items_id_seq from public, anon, authenticated;

commit;
