-- Marsad Al-Injazat — Phase S2-B3
-- Operational domains: meetings, curriculum planning, supervision, and achievement.
-- S2-B1 and S2-B2 must already exist. Runtime remains FastAPI/SQLite. RLS arrives in S2-C.

begin;

create table public.meetings (
    id bigint generated by default as identity primary key,
    school_id uuid not null,
    academic_year_id bigint not null,
    title text not null,
    meeting_type text not null default 'اجتماع قسم',
    meeting_date date not null,
    meeting_time time without time zone,
    location text,
    agenda text,
    discussion_summary text,
    notes text,
    status text not null default 'planned',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint meetings_title_nonblank check (btrim(title) <> ''),
    constraint meetings_status_check check (status in ('planned', 'held', 'cancelled')),
    constraint meetings_academic_year_fk
        foreign key (school_id, academic_year_id)
        references public.academic_years (school_id, id)
        on delete restrict,
    constraint meetings_school_id_id_key unique (school_id, id)
);

create index idx_meetings_scope
    on public.meetings (school_id, academic_year_id, meeting_date desc, id desc);

create table public.meeting_attendees (
    school_id uuid not null,
    meeting_id bigint not null,
    teacher_id bigint not null,
    attendance_status text not null default 'present',
    created_at timestamptz not null default now(),
    constraint meeting_attendees_pkey primary key (meeting_id, teacher_id),
    constraint meeting_attendees_status_check
        check (attendance_status in ('present', 'absent', 'excused')),
    constraint meeting_attendees_meeting_fk
        foreign key (school_id, meeting_id)
        references public.meetings (school_id, id)
        on delete cascade,
    constraint meeting_attendees_teacher_fk
        foreign key (school_id, teacher_id)
        references public.teachers (school_id, id)
        on delete cascade
);

create index idx_meeting_attendees_meeting
    on public.meeting_attendees (school_id, meeting_id, teacher_id);
create index idx_meeting_attendees_teacher
    on public.meeting_attendees (school_id, teacher_id, meeting_id);

create table public.meeting_decisions (
    id bigint generated by default as identity primary key,
    school_id uuid not null,
    meeting_id bigint not null,
    title text not null,
    responsible_teacher_id bigint,
    responsible_name text,
    due_date date,
    status text not null default 'new',
    notes text,
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint meeting_decisions_title_nonblank check (btrim(title) <> ''),
    constraint meeting_decisions_status_check
        check (status in ('new', 'in_progress', 'completed', 'cancelled')),
    constraint meeting_decisions_meeting_fk
        foreign key (school_id, meeting_id)
        references public.meetings (school_id, id)
        on delete cascade,
    constraint meeting_decisions_responsible_teacher_fk
        foreign key (school_id, responsible_teacher_id)
        references public.teachers (school_id, id)
        on delete set null (responsible_teacher_id)
);

create index idx_meeting_decisions_meeting
    on public.meeting_decisions (school_id, meeting_id, status, due_date);
create index idx_meeting_decisions_responsible
    on public.meeting_decisions (school_id, responsible_teacher_id)
    where responsible_teacher_id is not null;
create index idx_meeting_decisions_open
    on public.meeting_decisions (school_id, status, due_date);

create table public.curriculum_plans (
    id bigint generated by default as identity primary key,
    school_id uuid not null,
    academic_year_id bigint not null,
    title text not null,
    subject text not null,
    grade text not null,
    term text not null,
    owner_teacher_id bigint,
    start_date date,
    end_date date,
    notes text,
    status text not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint curriculum_plans_title_nonblank check (btrim(title) <> ''),
    constraint curriculum_plans_subject_nonblank check (btrim(subject) <> ''),
    constraint curriculum_plans_grade_nonblank check (btrim(grade) <> ''),
    constraint curriculum_plans_term_nonblank check (btrim(term) <> ''),
    constraint curriculum_plans_status_check
        check (status in ('active', 'completed', 'archived')),
    constraint curriculum_plans_academic_year_fk
        foreign key (school_id, academic_year_id)
        references public.academic_years (school_id, id)
        on delete restrict,
    constraint curriculum_plans_owner_teacher_fk
        foreign key (school_id, owner_teacher_id)
        references public.teachers (school_id, id)
        on delete set null (owner_teacher_id),
    constraint curriculum_plans_school_id_id_key unique (school_id, id)
);

create index idx_curriculum_plans_scope
    on public.curriculum_plans (school_id, academic_year_id, term, subject, grade, status);
create index idx_curriculum_plans_owner
    on public.curriculum_plans (school_id, owner_teacher_id)
    where owner_teacher_id is not null;

create table public.curriculum_units (
    id bigint generated by default as identity primary key,
    school_id uuid not null,
    plan_id bigint not null,
    title text not null,
    sequence integer not null default 0,
    planned_start date,
    planned_end date,
    progress_percent smallint not null default 0,
    status text not null default 'not_started',
    delay_reason text,
    notes text,
    responsible_teacher_id bigint,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint curriculum_units_title_nonblank check (btrim(title) <> ''),
    constraint curriculum_units_sequence_check check (sequence >= 0),
    constraint curriculum_units_progress_check check (progress_percent between 0 and 100),
    constraint curriculum_units_status_check
        check (status in ('not_started', 'in_progress', 'completed')),
    constraint curriculum_units_plan_fk
        foreign key (school_id, plan_id)
        references public.curriculum_plans (school_id, id)
        on delete cascade,
    constraint curriculum_units_responsible_teacher_fk
        foreign key (school_id, responsible_teacher_id)
        references public.teachers (school_id, id)
        on delete set null (responsible_teacher_id)
);

create index idx_curriculum_units_plan
    on public.curriculum_units (school_id, plan_id, sequence, id);
create index idx_curriculum_units_responsible
    on public.curriculum_units (school_id, responsible_teacher_id)
    where responsible_teacher_id is not null;
create index idx_curriculum_units_due
    on public.curriculum_units (school_id, status, planned_end, progress_percent);

create table public.supervision_visits (
    id bigint generated by default as identity primary key,
    school_id uuid not null,
    academic_year_id bigint not null,
    teacher_id bigint not null,
    visit_type text not null default 'زيارة صفية',
    visit_date date not null,
    period_label text,
    grade text,
    lesson_title text,
    objectives text,
    strengths text,
    development_areas text,
    recommendations text,
    followup_date date,
    followup_notes text,
    status text not null default 'planned',
    closed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint supervision_visits_status_check
        check (status in ('planned', 'completed', 'needs_followup', 'closed')),
    constraint supervision_visits_academic_year_fk
        foreign key (school_id, academic_year_id)
        references public.academic_years (school_id, id)
        on delete restrict,
    constraint supervision_visits_teacher_fk
        foreign key (school_id, teacher_id)
        references public.teachers (school_id, id)
        on delete restrict,
    constraint supervision_visits_school_id_id_key unique (school_id, id)
);

create index idx_supervision_visits_scope
    on public.supervision_visits (school_id, academic_year_id, status, visit_date desc, id desc);
create index idx_supervision_visits_teacher
    on public.supervision_visits (school_id, teacher_id, visit_date desc, id desc);

create table public.supervision_actions (
    id bigint generated by default as identity primary key,
    school_id uuid not null,
    visit_id bigint not null,
    title text not null,
    responsible_teacher_id bigint,
    due_date date,
    status text not null default 'new',
    notes text,
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint supervision_actions_title_nonblank check (btrim(title) <> ''),
    constraint supervision_actions_status_check
        check (status in ('new', 'in_progress', 'completed', 'cancelled')),
    constraint supervision_actions_visit_fk
        foreign key (school_id, visit_id)
        references public.supervision_visits (school_id, id)
        on delete cascade,
    constraint supervision_actions_responsible_teacher_fk
        foreign key (school_id, responsible_teacher_id)
        references public.teachers (school_id, id)
        on delete set null (responsible_teacher_id)
);

create index idx_supervision_actions_visit
    on public.supervision_actions (school_id, visit_id, status, due_date);
create index idx_supervision_actions_responsible
    on public.supervision_actions (school_id, responsible_teacher_id)
    where responsible_teacher_id is not null;
create index idx_supervision_actions_open
    on public.supervision_actions (school_id, status, due_date);

create table public.achievement_assessments (
    id bigint generated by default as identity primary key,
    school_id uuid not null,
    academic_year_id bigint not null,
    title text not null,
    assessment_type text not null default 'اختبار',
    subject text not null,
    grade text not null,
    assessment_date date not null,
    term text not null,
    teacher_id bigint,
    max_score numeric(12,4) not null,
    student_count integer not null default 0,
    average_score numeric(12,4),
    highest_score numeric(12,4),
    lowest_score numeric(12,4),
    mastery_threshold_pct numeric(5,2) not null default 60,
    mastered_count integer not null default 0,
    near_mastery_count integer not null default 0,
    intervention_count integer not null default 0,
    notes text,
    status text not null default 'draft',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint achievement_assessments_title_nonblank check (btrim(title) <> ''),
    constraint achievement_assessments_subject_nonblank check (btrim(subject) <> ''),
    constraint achievement_assessments_grade_nonblank check (btrim(grade) <> ''),
    constraint achievement_assessments_term_nonblank check (btrim(term) <> ''),
    constraint achievement_assessments_max_score_check check (max_score > 0),
    constraint achievement_assessments_student_count_check check (student_count >= 0),
    constraint achievement_assessments_average_check
        check (average_score is null or (average_score >= 0 and average_score <= max_score)),
    constraint achievement_assessments_highest_check
        check (highest_score is null or (highest_score >= 0 and highest_score <= max_score)),
    constraint achievement_assessments_lowest_check
        check (lowest_score is null or (lowest_score >= 0 and lowest_score <= max_score)),
    constraint achievement_assessments_mastery_threshold_check
        check (mastery_threshold_pct between 0 and 100),
    constraint achievement_assessments_mastered_count_check check (mastered_count >= 0),
    constraint achievement_assessments_near_mastery_count_check check (near_mastery_count >= 0),
    constraint achievement_assessments_intervention_count_check check (intervention_count >= 0),
    constraint achievement_assessments_bucket_total_check
        check (mastered_count + near_mastery_count + intervention_count <= student_count),
    constraint achievement_assessments_status_check
        check (status in ('draft', 'recorded', 'reviewed')),
    constraint achievement_assessments_academic_year_fk
        foreign key (school_id, academic_year_id)
        references public.academic_years (school_id, id)
        on delete restrict,
    constraint achievement_assessments_teacher_fk
        foreign key (school_id, teacher_id)
        references public.teachers (school_id, id)
        on delete set null (teacher_id),
    constraint achievement_assessments_school_id_id_key unique (school_id, id)
);

create index idx_achievement_assessments_scope
    on public.achievement_assessments
       (school_id, academic_year_id, term, subject, grade, assessment_date desc, id desc);
create index idx_achievement_assessments_teacher
    on public.achievement_assessments (school_id, teacher_id, assessment_date desc, id desc)
    where teacher_id is not null;

create table public.achievement_assessment_standards (
    assessment_id bigint primary key,
    school_id uuid not null,
    mastery_reference_source text not null default '',
    mastery_reference_year text,
    mastery_reference_note text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint achievement_assessment_standards_assessment_fk
        foreign key (school_id, assessment_id)
        references public.achievement_assessments (school_id, id)
        on delete cascade
);

create index idx_achievement_assessment_standards_assessment
    on public.achievement_assessment_standards (school_id, assessment_id);
create index idx_achievement_assessment_standards_source
    on public.achievement_assessment_standards (school_id, mastery_reference_source);

create table public.achievement_actions (
    id bigint generated by default as identity primary key,
    school_id uuid not null,
    assessment_id bigint not null,
    action_type text not null default 'remedial',
    title text not null,
    target_group text,
    responsible_teacher_id bigint,
    start_date date,
    due_date date,
    status text not null default 'new',
    baseline_indicator text,
    target_indicator text,
    outcome_indicator text,
    notes text,
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint achievement_actions_title_nonblank check (btrim(title) <> ''),
    constraint achievement_actions_type_check
        check (action_type in ('remedial', 'enrichment', 'followup')),
    constraint achievement_actions_status_check
        check (status in ('new', 'in_progress', 'completed', 'cancelled')),
    constraint achievement_actions_assessment_fk
        foreign key (school_id, assessment_id)
        references public.achievement_assessments (school_id, id)
        on delete cascade,
    constraint achievement_actions_responsible_teacher_fk
        foreign key (school_id, responsible_teacher_id)
        references public.teachers (school_id, id)
        on delete set null (responsible_teacher_id),
    constraint achievement_actions_school_id_id_key unique (school_id, id)
);

create index idx_achievement_actions_assessment
    on public.achievement_actions (school_id, assessment_id, status, due_date);
create index idx_achievement_actions_responsible
    on public.achievement_actions (school_id, responsible_teacher_id)
    where responsible_teacher_id is not null;
create index idx_achievement_actions_open
    on public.achievement_actions (school_id, status, due_date);

create table public.achievement_action_metrics (
    action_id bigint primary key,
    school_id uuid not null,
    metric_name text not null,
    unit text not null default '',
    direction text not null default 'higher_better',
    baseline_value numeric(18,6) not null,
    target_value numeric(18,6) not null,
    outcome_value numeric(18,6),
    measured_at date,
    reference_source text,
    reference_year text,
    reference_note text,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint achievement_action_metrics_direction_check
        check (direction in ('higher_better', 'lower_better')),
    constraint achievement_action_metrics_measurement_check
        check (
            (outcome_value is null and measured_at is null)
            or (outcome_value is not null and measured_at is not null)
        ),
    constraint achievement_action_metrics_action_fk
        foreign key (school_id, action_id)
        references public.achievement_actions (school_id, id)
        on delete cascade
);

create index idx_achievement_action_metrics_action
    on public.achievement_action_metrics (school_id, action_id);
create index idx_achievement_action_metrics_status
    on public.achievement_action_metrics (school_id, direction, outcome_value);

-- S2-B3 remains deny-by-default until S2-C installs RLS policies.
revoke all on table public.meetings from public, anon, authenticated;
revoke all on table public.meeting_attendees from public, anon, authenticated;
revoke all on table public.meeting_decisions from public, anon, authenticated;
revoke all on table public.curriculum_plans from public, anon, authenticated;
revoke all on table public.curriculum_units from public, anon, authenticated;
revoke all on table public.supervision_visits from public, anon, authenticated;
revoke all on table public.supervision_actions from public, anon, authenticated;
revoke all on table public.achievement_assessments from public, anon, authenticated;
revoke all on table public.achievement_assessment_standards from public, anon, authenticated;
revoke all on table public.achievement_actions from public, anon, authenticated;
revoke all on table public.achievement_action_metrics from public, anon, authenticated;

revoke all on sequence public.meetings_id_seq from public, anon, authenticated;
revoke all on sequence public.meeting_decisions_id_seq from public, anon, authenticated;
revoke all on sequence public.curriculum_plans_id_seq from public, anon, authenticated;
revoke all on sequence public.curriculum_units_id_seq from public, anon, authenticated;
revoke all on sequence public.supervision_visits_id_seq from public, anon, authenticated;
revoke all on sequence public.supervision_actions_id_seq from public, anon, authenticated;
revoke all on sequence public.achievement_assessments_id_seq from public, anon, authenticated;
revoke all on sequence public.achievement_actions_id_seq from public, anon, authenticated;

commit;
