-- Marsad Al-Injazat — Phase S2-B4
-- Settings, requests, documents, events, media, teacher links, and activity log.
-- S2-B1..S2-B3 must already exist. Runtime remains FastAPI/SQLite.
-- This migration does not create RLS policies; browser roles stay revoked until S2-C.

begin;

create table public.school_settings (
    school_id uuid not null,
    key text not null,
    value jsonb not null,
    updated_at timestamptz not null default now(),
    updated_by uuid,
    constraint school_settings_pkey primary key (school_id, key),
    constraint school_settings_key_nonblank check (btrim(key) <> ''),
    constraint school_settings_school_fk
        foreign key (school_id)
        references public.schools (id)
        on delete cascade,
    constraint school_settings_updated_by_fk
        foreign key (school_id, updated_by)
        references public.school_memberships (school_id, user_id)
        on delete set null (updated_by)
);

create index idx_school_settings_updated_by
    on public.school_settings (school_id, updated_by)
    where updated_by is not null;

create table public.upload_requests (
    id bigint generated by default as identity primary key,
    school_id uuid not null,
    academic_year_id bigint not null,
    teacher_id bigint not null,
    request_type text not null,
    subject text not null,
    grade text not null,
    title text not null,
    deadline date,
    notes text,
    allowed_files text not null default 'PDF / Word / Excel',
    token_hash text not null,
    status text not null default 'waiting_upload',
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint upload_requests_request_type_nonblank check (btrim(request_type) <> ''),
    constraint upload_requests_subject_nonblank check (btrim(subject) <> ''),
    constraint upload_requests_grade_nonblank check (btrim(grade) <> ''),
    constraint upload_requests_title_nonblank check (btrim(title) <> ''),
    constraint upload_requests_allowed_files_nonblank check (btrim(allowed_files) <> ''),
    constraint upload_requests_token_hash_nonblank check (btrim(token_hash) <> ''),
    constraint upload_requests_token_hash_key unique (token_hash),
    constraint upload_requests_status_check check (
        status in ('waiting_upload', 'received', 'review', 'approved', 'needs_revision', 'late', 'cancelled')
    ),
    constraint upload_requests_academic_year_fk
        foreign key (school_id, academic_year_id)
        references public.academic_years (school_id, id)
        on delete restrict,
    constraint upload_requests_teacher_fk
        foreign key (school_id, teacher_id)
        references public.teachers (school_id, id)
        on delete restrict,
    constraint upload_requests_school_id_id_key unique (school_id, id)
);

create index idx_upload_requests_scope
    on public.upload_requests (school_id, academic_year_id, status, deadline, id);
create index idx_upload_requests_teacher
    on public.upload_requests (school_id, teacher_id, academic_year_id, id);
create index idx_upload_requests_expires
    on public.upload_requests (school_id, expires_at, status);

create table public.documents (
    id bigint generated by default as identity primary key,
    school_id uuid not null,
    academic_year_id bigint not null,
    request_id bigint,
    teacher_id bigint,
    title text not null,
    category text not null,
    subject text,
    grade text,
    original_name text not null,
    mime_type text,
    size_bytes bigint not null default 0,
    storage_provider text not null,
    storage_bucket text,
    storage_path text,
    external_url text,
    status text not null default 'inbox',
    uploaded_at timestamptz not null default now(),
    approved_at timestamptz,
    constraint documents_title_nonblank check (btrim(title) <> ''),
    constraint documents_category_nonblank check (btrim(category) <> ''),
    constraint documents_original_name_nonblank check (btrim(original_name) <> ''),
    constraint documents_size_bytes_check check (size_bytes >= 0),
    constraint documents_storage_provider_check check (
        storage_provider in ('supabase', 'google_drive', 'legacy_local')
    ),
    constraint documents_academic_year_fk
        foreign key (school_id, academic_year_id)
        references public.academic_years (school_id, id)
        on delete restrict,
    constraint documents_request_fk
        foreign key (school_id, request_id)
        references public.upload_requests (school_id, id)
        on delete set null (request_id),
    constraint documents_teacher_fk
        foreign key (school_id, teacher_id)
        references public.teachers (school_id, id)
        on delete set null (teacher_id)
);

create index idx_documents_scope
    on public.documents (school_id, academic_year_id, status, uploaded_at desc, id desc);
create index idx_documents_request
    on public.documents (school_id, request_id, id)
    where request_id is not null;
create index idx_documents_teacher
    on public.documents (school_id, teacher_id, academic_year_id, id)
    where teacher_id is not null;
create index idx_documents_storage
    on public.documents (school_id, storage_provider, storage_bucket, storage_path);

create table public.events (
    id bigint generated by default as identity primary key,
    school_id uuid not null,
    academic_year_id bigint not null,
    title text not null,
    event_type text not null,
    event_date date not null,
    location text,
    audience text,
    participant_count integer not null default 0,
    goals text,
    summary text,
    outcomes text,
    recommendations text,
    cover_tone text not null default 'teal',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint events_title_nonblank check (btrim(title) <> ''),
    constraint events_event_type_nonblank check (btrim(event_type) <> ''),
    constraint events_participant_count_check check (participant_count >= 0),
    constraint events_academic_year_fk
        foreign key (school_id, academic_year_id)
        references public.academic_years (school_id, id)
        on delete restrict,
    constraint events_school_id_id_key unique (school_id, id)
);

create index idx_events_scope
    on public.events (school_id, academic_year_id, event_date desc, id desc);
create index idx_events_type
    on public.events (school_id, academic_year_id, event_type, event_date desc);

create table public.event_media (
    id bigint generated by default as identity primary key,
    school_id uuid not null,
    event_id bigint not null,
    original_name text not null,
    mime_type text,
    size_bytes bigint not null default 0,
    storage_provider text not null,
    storage_bucket text,
    storage_path text,
    external_url text,
    caption text not null default '',
    position integer not null default 0,
    is_cover boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint event_media_original_name_nonblank check (btrim(original_name) <> ''),
    constraint event_media_size_bytes_check check (size_bytes >= 0),
    constraint event_media_position_check check (position >= 0),
    constraint event_media_storage_provider_check check (
        storage_provider in ('supabase', 'google_drive', 'legacy_local')
    ),
    constraint event_media_event_fk
        foreign key (school_id, event_id)
        references public.events (school_id, id)
        on delete cascade
);

create index idx_event_media_event
    on public.event_media (school_id, event_id, position, id);
create unique index uq_event_media_one_cover_per_event
    on public.event_media (school_id, event_id)
    where is_cover;
create index idx_event_media_storage
    on public.event_media (school_id, storage_provider, storage_bucket, storage_path);

create table public.event_teacher_links (
    school_id uuid not null,
    event_id bigint not null,
    teacher_id bigint not null,
    role text not null default 'مشارك',
    created_at timestamptz not null default now(),
    constraint event_teacher_links_pkey primary key (event_id, teacher_id),
    constraint event_teacher_links_role_nonblank check (btrim(role) <> ''),
    constraint event_teacher_links_event_fk
        foreign key (school_id, event_id)
        references public.events (school_id, id)
        on delete cascade,
    constraint event_teacher_links_teacher_fk
        foreign key (school_id, teacher_id)
        references public.teachers (school_id, id)
        on delete cascade
);

create index idx_event_teacher_links_event
    on public.event_teacher_links (school_id, event_id, teacher_id);
create index idx_event_teacher_links_teacher
    on public.event_teacher_links (school_id, teacher_id, event_id);

create table public.activities (
    id bigint generated by default as identity primary key,
    school_id uuid not null,
    academic_year_id bigint,
    actor_user_id uuid,
    activity_type text not null,
    title text not null,
    detail text,
    entity_type text,
    entity_id bigint,
    created_at timestamptz not null default now(),
    constraint activities_activity_type_nonblank check (btrim(activity_type) <> ''),
    constraint activities_title_nonblank check (btrim(title) <> ''),
    constraint activities_academic_year_fk
        foreign key (school_id, academic_year_id)
        references public.academic_years (school_id, id)
        on delete restrict,
    constraint activities_actor_membership_fk
        foreign key (school_id, actor_user_id)
        references public.school_memberships (school_id, user_id)
        on delete set null (actor_user_id)
);

create index idx_activities_created
    on public.activities (school_id, created_at desc, id desc);
create index idx_activities_year
    on public.activities (school_id, academic_year_id, created_at desc, id desc)
    where academic_year_id is not null;
create index idx_activities_actor
    on public.activities (school_id, actor_user_id, created_at desc)
    where actor_user_id is not null;
create index idx_activities_entity
    on public.activities (school_id, entity_type, entity_id, created_at desc)
    where entity_type is not null and entity_id is not null;

-- S2-B4 remains deny-by-default. Some Supabase projects may auto-enable RLS
-- on newly-created tables via an external event trigger; this migration itself
-- does not create policies or enable RLS. S2-C remains the authorization phase.
revoke all on table public.school_settings from public, anon, authenticated;
revoke all on table public.upload_requests from public, anon, authenticated;
revoke all on table public.documents from public, anon, authenticated;
revoke all on table public.events from public, anon, authenticated;
revoke all on table public.event_media from public, anon, authenticated;
revoke all on table public.event_teacher_links from public, anon, authenticated;
revoke all on table public.activities from public, anon, authenticated;

revoke all on sequence public.upload_requests_id_seq from public, anon, authenticated;
revoke all on sequence public.documents_id_seq from public, anon, authenticated;
revoke all on sequence public.events_id_seq from public, anon, authenticated;
revoke all on sequence public.event_media_id_seq from public, anon, authenticated;
revoke all on sequence public.activities_id_seq from public, anon, authenticated;

commit;
